name: apps
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.0.1
  flutter_background_service: ^5.0.5
  flutter_background_service_ios: ^5.0.0
  flutter_local_notifications: ^16.2.0
  device_info_plus: ^9.1.1
  url_launcher: ^6.2.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  http: ^1.1.2
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
